"""
PR preparation -- the Level 3 of CI/CD adoption.

Design principle, consistent with the rest of APIHealer: the tool does NOT
"control" your git host. It prepares everything a pull request needs -- a branch,
a descriptive commit, and a PR body built from the VerificationReport -- using
plain git, which works the same on Azure DevOps, GitHub, GitLab or a bare repo.
Opening the PR against a specific host is a thin, host-specific step that needs
YOUR credentials; APIHealer leaves that socket ready rather than guessing your
org, project, or auth. Same stance as the LLM: APIHealer prepares; you plug in
credentials.

What this module does (all testable without any host credentials):
  - compute a branch name from the API name and verification level
  - run `git checkout -b`, stage the changed files, and commit with a message
    that summarizes the remediation
  - render a PR title and body (Markdown) from the RemediationResult

What it deliberately does NOT do here:
  - authenticate to Azure DevOps / GitHub and POST the PR. That belongs in a
    host adapter the user configures. `pr_push_hint()` returns the exact command
    to finish it by hand or in a pipeline.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

from ..adapters.base import RemediationResult


@dataclass
class PreparedPR:
    branch: str
    title: str
    body: str
    committed: bool
    notes: list[str]


def branch_name(api_name: str, level: str) -> str:
    safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in api_name.lower()).strip("-")
    return f"apihealer/remediate-{safe or 'api'}-{level}"


def pr_title(api_name: str, result: RemediationResult) -> str:
    verb = {
        "build": "Verified remediation",
        "inferred_build": "Inferred remediation",
        "syntax_only": "Suggested remediation",
    }.get(result.verification.level.value, "Remediation")
    return f"APIHealer: {verb} for '{api_name}' contract change"


def pr_body(api_name: str, result: RemediationResult) -> str:
    """Build the PR description from the VerificationReport. This is the point:
    the reviewer sees confidence, evidence and residual risks up front."""
    v = result.verification
    pct = round(result.confidence * 100)
    lines = [
        f"## APIHealer remediation for `{api_name}`",
        "",
        f"A breaking change in the API contract was detected and remediated "
        f"automatically. **This PR needs human review** before merging.",
        "",
        f"- **Verification level:** `{v.level.value}`",
        f"- **Confidence:** {pct}%",
        f"- **Applied:** {'yes' if result.applied else 'no (preview)'}",
        "",
    ]
    if result.files_changed:
        lines.append("### Files changed")
        for f in result.files_changed:
            lines.append(f"- `{f}`")
        lines.append("")
    if result.confidence_factors:
        lines.append("### Why this confidence")
        for factor in result.confidence_factors:
            lines.append(f"- `{factor}`")
        lines.append("")
    if v.evidence:
        lines.append("### Evidence")
        for e in v.evidence:
            lines.append(f"- {e}")
        lines.append("")
    if v.remaining_risks:
        lines.append("### What a passing build still can't prove")
        for r in v.remaining_risks:
            lines.append(f"- {r}")
        lines.append("")
    lines.append("---")
    lines.append("_Generated by APIHealer. Verification-aware: the confidence "
                 "and residual risks above describe exactly how much of this fix "
                 "is proven versus inferred._")
    return "\n".join(lines)


def commit_message(api_name: str, result: RemediationResult) -> str:
    pct = round(result.confidence * 100)
    level = result.verification.level.value
    subject = f"APIHealer: remediate '{api_name}' breaking contract change"
    body = (
        f"Verification level: {level}\n"
        f"Confidence: {pct}%\n"
        f"Files changed: {', '.join(result.files_changed) or '(none)'}\n\n"
        "This change was produced automatically and needs human review. "
        "See the PR description for evidence and residual risks."
    )
    return f"{subject}\n\n{body}"


def _git(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=str(cwd),
                          capture_output=True, text=True)


def prepare_pr(project_root: Path, api_name: str, result: RemediationResult) -> PreparedPR:
    """Create the branch, stage the changed files, and commit. Host-agnostic;
    uses plain git so it works anywhere. Never pushes -- that needs credentials."""
    level = result.verification.level.value
    branch = branch_name(api_name, level)
    title = pr_title(api_name, result)
    body = pr_body(api_name, result)
    notes: list[str] = []

    # Is this a git repo?
    check = _git(["rev-parse", "--is-inside-work-tree"], project_root)
    if check.returncode != 0:
        notes.append("Not a git repository, so nothing was committed. "
                     "The PR title and body were still generated.")
        return PreparedPR(branch, title, body, committed=False, notes=notes)

    # Create/switch to the branch.
    co = _git(["checkout", "-b", branch], project_root)
    if co.returncode != 0:
        # branch may exist; try switching
        sw = _git(["checkout", branch], project_root)
        if sw.returncode != 0:
            notes.append(f"Could not create or switch to branch '{branch}': {co.stderr.strip()}")
            return PreparedPR(branch, title, body, committed=False, notes=notes)

    # Stage the changed files (fall back to -A if paths are logical labels).
    real_files = [f for f in result.files_changed if (project_root / f).exists()]
    if real_files:
        _git(["add", *real_files], project_root)
    else:
        _git(["add", "-A"], project_root)

    # Commit.
    cm = _git(["commit", "-m", commit_message(api_name, result)], project_root)
    if cm.returncode != 0:
        notes.append(f"Nothing committed: {cm.stdout.strip() or cm.stderr.strip()}")
        return PreparedPR(branch, title, body, committed=False, notes=notes)

    notes.append(f"Committed the remediation on branch '{branch}'.")
    return PreparedPR(branch, title, body, committed=True, notes=notes)


def pr_push_hint(branch: str) -> str:
    """The one command that finishes the flow -- run by the user or a pipeline
    that has credentials. APIHealer prepares; you push."""
    return (
        f"git push -u origin {branch}\n"
        "# then open the PR:\n"
        "#   Azure DevOps:  az repos pr create --source-branch "
        f"{branch} --title \"<title>\" --description @pr-body.md\n"
        f"#   GitHub CLI:    gh pr create --head {branch} --title \"<title>\" --body-file pr-body.md"
    )
